import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
import Nav from './component/Nav'
import { Maven_Pro } from 'next/font/google'
import Footer from './component/Footer'

 
const inter = Maven_Pro({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}