import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
import Nav from './component/Nav'
import { Raleway } from 'next/font/google'
import Footer from './component/Footer'
import Providers from './component/shopping icon/Provider'
import { ClerkProvider } from '@clerk/nextjs'
import Clerk from './component/Clerk'

const sora = Raleway({ subsets: ["latin"] });

// const inter = Maven_Pro({
//   subsets: ['latin'],
//   // weight: ["400", "500", "600", "700", "800", "900"]
// })

export const metadata: Metadata = {
  title: 'Hackathone',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className='wrapper mx-auto'>
        <Nav/>
        <Clerk/>
        {children}
        <Footer/>
        </body>
    </html>
    </ClerkProvider>
  )
}